apiVersion: v1
kind: Namespace
metadata:
  name: ai-training
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gpu-training-sa
  namespace: ai-training
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gpu-training-role
  namespace: ai-training
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gpu-training-rolebinding
  namespace: ai-training
subjects:
- kind: ServiceAccount
  name: gpu-training-sa
  namespace: ai-training
roleRef:
  kind: Role
  name: gpu-training-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: gpu-training-job
  namespace: ai-training
spec:
  template:
    spec:
      serviceAccountName: gpu-training-sa
      containers:
      - name: training-container
        image: nvidia/cuda:11.8.0-runtime-ubuntu22.04
        command: ["python", "/app/train.py"]
        resources:
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: training-code
          mountPath: /app
      volumes:
      - name: training-code
        configMap:
          name: training-code
      restartPolicy: Never
  backoffLimit: 4 